version: '3'
services:
    postgres:
        image: postgres:10
        environment:
            POSTGRES_USER: inmanta
            POSTGRES_PASSWORD: inmanta

    inmanta-server:
        build:
            context: "./server"
        ports:
            - "8888:8888"
        links:
            - postgres
        volumes:
            - inmanta-data:/var/lib/inmanta
            - ./test-project:/home/inmanta/test-project
        depends_on:
            - "postgres"

    agent-1:
        build:
            context: "./agent"
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        privileged: true
        links:
            - inmanta-server

    agent-2:
        build:
            context: "./agent"
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        privileged: true
        links:
            - inmanta-server

volumes:
    inmanta-data:
