version: '3'
services:
    postgres:
        container_name: inmanta_quickstart_postgres
        image: postgres:10
        environment:
            POSTGRES_USER: inmanta
            POSTGRES_PASSWORD: inmanta
        networks:
            testing_net:
                ipv4_address: 172.28.0.2

    inmanta-server:
        container_name: inmanta_quickstart_server
        image: inmanta-server
        build:
            context: "./server"
            dockerfile: Dockerfile-el${EL_VERSION:-7}
            args: 
                RELEASE: ${RELEASE:-stable}
        ports:
            - "8888:8888"
        volumes:
            - ssh-data:/home/inmanta/.shared
            - ./quickstart-project:/home/inmanta/quickstart-project:Z
        depends_on:
            - "postgres"
        networks:
            testing_net:
                ipv4_address: 172.28.0.3

    agent-1:
        container_name: inmanta_quickstart_agent_1
        image: inmanta-agent
        build:
            context: "./agent"
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ssh-data:/root/.ssh
        privileged: true
        depends_on:
            - "inmanta-server"
        networks:
            testing_net:
                ipv4_address: 172.28.0.4
        ports:
            - "8080:80"

    agent-2:
        container_name: inmanta_quickstart_agent_2
        image: inmanta-agent
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ssh-data:/root/.ssh
        privileged: true
        depends_on:
            - "inmanta-server"
        networks:
            testing_net:
                ipv4_address: 172.28.0.5

volumes:
    ssh-data:

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
