version: '3'
services:
    inmanta:
        build:
            context: "./server"
        ports:
            - "8888:8888"
        links:
            - postgres
        volumes:
            - inmanta-data:/var/lib/inmanta
            - ./test-project:/home/inmanta/test-project
        depends_on:
            - "postgres"

    postgres:
        image: postgres:10
        environment:
            POSTGRES_USER: inmanta
            POSTGRES_PASSWORD: inmanta

volumes:
    inmanta-data:
